### ISSUE TITLE
May I modify your code for my NAS(Synology)?

### ISSUE THREAD

**Issue by dhckdgjs** [Matsuo3rd/bose-soundtouch-aux-keepalive#1]
First of all, thank you for your useful script :)
Your code works like a charm in Mac!

But my NAS(Synology task scheduler) can't run your code.
(Synology could basically only run script written by the Ash)

So I modified your code a little bit for my NAS.
If somebody needs the code for Synology task scheduler like me, use my version like as below.
(I'm not familiar with a script, so please excuse something wrong in the script)

* Synology needs another packages for their SSH - bootstrap, bash, xmllint etc

#!/bin/bash
PATH=/opt/bin:/usr/bin/:/opt/bin/bash
# Script as below
soundtouch_ip=PUTSOUNDTOUCHIPHERE
source=$(curl -s http://$soundtouch_ip:8090/now_playing | xmllint --xpath 'string(/nowPlaying/@source)' -)
if [ $source = "AUX" ]
then
echo SoundTouch mode is AUX: keep-alive
curl -s -o /dev/null --request POST --header "Content-Type: application/xml" --data '<key state="press" sender="Gabbo">THUMBS_UP</key>' http://$soundtouch_ip:8090/key
elif [ $source = "STANDBY" ]
then
echo SoundTouch mode is STANDBY: switch to AUX
curl -s -o /dev/null --request POST --header "Content-Type: application/xml" --data '<ContentItem source="AUX" sourceAccount="AUX"></ContentItem>' http://$soundtouch_ip:8090/select
fi

**Comment by Matsuo3rd** [comment]
Hello dhckdgjs,

For the sake of clarification, you just have added the first 2 lines of your script:
#!/bin/bash
PATH=/opt/bin:/usr/bin/:/opt/bin/bash

and deleted the #!/bin/sh line. Correct?

**Comment by dhckdgjs** [comment]
Hi, Matsuo3rd :)

Yes. That's right.
I added only 2 lines. And also deleted the 1st line.(#!/bin/sh)
That's it.

**Comment by Matsuo3rd** [comment]
Hello @dhckdgjs,
I have updated the script accordingly. Thanks for your input.

**Comment by Rocco83** [comment]
Hi,

Resuming the old thread. Why can't you change the path when calling the script?
