### ISSUE TITLE
Bose Soundlink Air and Airport Express

### ISSUE THREAD

**Issue by QandnotU** [Matsuo3rd/bose-soundtouch-aux-keepalive#3]
Recently Apple updated the firmware on the Airport Express with Airplay 2 compatibility. I’ve had a Bose Soundlink Air collecting dust and thought this would be the perfect opportunity to turn it into an Airplay 2 device (via Aux). Unfortunately I’m running up against the same issue where you can’t disable the auto off feature, so I’m hoping I could modify your script for my situation. The Bose Soundlink Air does have WiFi, any thoughts would be much appreciated.

**Comment by Matsuo3rd** [comment]
Unfortunately your Bose Soundlink Air does not support the Bose Soundtouch API (different set of Bose products). Hence this script will not be helpful.
