### ISSUE TITLE
The script works well with the BOSE Sountouch wireless adapter

### ISSUE THREAD

**Issue by MagicFab** [Matsuo3rd/bose-soundtouch-aux-keepalive#4]
Hello - I am glad to report this works well with the [BOSE SoundTouch Wireless Link adapter](https://www.bose.com/en_us/products/speakers/smart_home/soundtouch-adapter.html).

It's particularly useful as this adapter does not come with a remote control.

Thanks a lot for sharing this!

**Comment by Matsuo3rd** [comment]
Thanks for reporting. Documentation updated.
